[Settings]
ID = "ganslandt.xyz"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  environment = { NODE_VERSION = "10" }
  publish = "dist/"
  command = "yarn run build"

# Everything redirects to index.html for now
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301

[[headers]]
  for = "*"
  [headers.values]
    Link = '''
    </fonts/IBMPlexSans-Regular-Latin1-subset.woff2>; rel=preload; as=font; crossorigin=anonymous,
    </fonts/CanelaDeck-Bold-Web-subset.woff2>; rel=preload; as=font; crossorigin=anonymous
    '''
