[Settings]
ID = "ganslandt.xyz"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  publish = "dist/"
  command = "yarn run build"

# Everything redirects to index.html for now
[[redirects]]
  from = "/*"
  to = "/"
  status = 301
