name: CI
on: [push]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Install NPM dependencies"
        run: "yarn install"
      - name: "Build"
        run: "yarn build"
        env:
            PASSWORD: ${{ secrets.PASSWORD }}
      - name: "Deploy"
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ganslandt.xyz
          username: gansland
          server-dir: "public_html/"
          local-dir: "./dist/"
          password: ${{ secrets.FTP_PASSWORD }}
